### PR TITLE
Run on client-side only to avoid server errors

### PR DESCRIPTION
**Pull request by orionzleon**
Also removes some unused code.

### CODE REVIEW

**Comment by hamarb123** [comment]
What is the advantage of doing this? Can the mod still be included in a server's mod files and be ignored if this is done, like it can currently?

**Comment by orionzleon** [comment]
With this change, the mod will no longer be loaded if ran on a dedicated server (even if its in the `mods` folder), reducing startup time

**Comment by caoimhebyrne** [comment]
I believe this is quite a useless change.

**Comment by orionzleon** [comment]
Can this just be changed? My server is causing errors when using a modpack
that has this mod

**Comment by hamarb123** [comment]
> Can this just be changed? My server is causing errors when using a modpack that has this mod

You only just indicated that this was potentially causing issues. Please try the following before we consider this change: 1. try removing just this mod alone from the modpack files, and seeing if it launches, 2. if that makes it not fail: please open a new issue with the error log.

**Pull request closed without merging**
